### ISSUE TITLE
Menu desaparece

### ISSUE THREAD

**Issue by VictorHugoDuranS** [BangKwn/el-bosque-del-ciclo-verde#3]
Cuando selecciono el menu y despues selecciono inicio desaparece el boton de menu, reaparece hasta que salgo y entro de la aplicacion

**Comment by BangKwn** [comment]
> Cuando selecciono el menu y despues selecciono inicio desaparece el boton de menu, reaparece hasta que salgo y entro de la aplicacion

solucionado
